// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsTS7W1MrunUyJUDZfP1jI9pODaSaBaAw',
    appId: '1:37388942593:web:269a268c64afe66284af00',
    messagingSenderId: '37388942593',
    projectId: 'docapp-62a21',
    authDomain: 'docapp-62a21.firebaseapp.com',
    storageBucket: 'docapp-62a21.firebasestorage.app',
    measurementId: 'G-25ND77NK9F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP2vrBoUv_VGPS9AqliyA3YCNSj3eYRd0',
    appId: '1:37388942593:ios:8daa430dc647acc984af00',
    messagingSenderId: '37388942593',
    projectId: 'docapp-62a21',
    storageBucket: 'docapp-62a21.firebasestorage.app',
    androidClientId: '37388942593-t6pjgd1omd6vdj1q4ue7c3ukebb942co.apps.googleusercontent.com',
    iosClientId: '37388942593-8cep8fain624joj5vbqnd42fkmvrjvth.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP2vrBoUv_VGPS9AqliyA3YCNSj3eYRd0',
    appId: '1:37388942593:ios:8daa430dc647acc984af00',
    messagingSenderId: '37388942593',
    projectId: 'docapp-62a21',
    storageBucket: 'docapp-62a21.firebasestorage.app',
    androidClientId: '37388942593-t6pjgd1omd6vdj1q4ue7c3ukebb942co.apps.googleusercontent.com',
    iosClientId: '37388942593-8cep8fain624joj5vbqnd42fkmvrjvth.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsTS7W1MrunUyJUDZfP1jI9pODaSaBaAw',
    appId: '1:37388942593:web:60ffcfc8a9483e9184af00',
    messagingSenderId: '37388942593',
    projectId: 'docapp-62a21',
    authDomain: 'docapp-62a21.firebaseapp.com',
    storageBucket: 'docapp-62a21.firebasestorage.app',
    measurementId: 'G-W9G76E38KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRE2a1rvFiWKblKxcxipeBYnNjEKXzTDk',
    appId: '1:37388942593:android:012a322c7585bfd184af00',
    messagingSenderId: '37388942593',
    projectId: 'docapp-62a21',
    storageBucket: 'docapp-62a21.firebasestorage.app',
  );
}
